---
title: "solve_objective_inverse"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{solve_objective_inverse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(SABER)
library(readr)
library(dplyr)
```

```{r}
wavelength <- seq(400, 800, 5)
```

## Bottom Rrs

```{r}
rrs_end_member <- read_csv(fs::path_package("SABER", "extdata", "rb_endmembers_algae-wise.csv"))
end_member_fraction <- c(0.25, 0.25, 0.5)

rrs_bottom <- rrs_bottom_lmm(
  rrs_end_member = rrs_end_member,
  end_member_fraction = end_member_fraction,
  wavelength = wavelength,
  verbose = T
)

# rrs_bottom
```

## Lee 1999 forward model

Parameter for Lee 1998 forward model with IOPs

```{r}
# Create IOP data frame
a <- read_csv(fs::path_package("SABER", "data", "rb_retrieve_demo_a.csv"))
bb <- read_csv(fs::path_package("SABER", "data", "rb_retrieve_demo_bb.csv"))

iop <- parse_iop(
  a = a,
  bb = bb,
  wavelength = wavelength,
  verbose = T
)

# iop
```

```{r}
test <- lee98_forward(
  wavelength = wavelength,
  iop = iop,
  view = 40,
  sun = 20,
  optically_shallow = T,
  h_w = 2,
  rrs_bottom = rrs_bottom,
  verbose = T
)
```

Parameter for Lee 1998 forward model with OACs

```{r}
oac <- tibble(
  "chl" = 0.1, # [mg/m^3]
  "bbp_550" = 0.00726002,
  "ag_440" = 1,
  "ag_s_g" = 0.015,
  "ag_s_d" = 0.0116,
  "bb_gamma" = 1
)

iop <- iop_from_oac(
  wavelength,
  oac,
  verbose = T
)
```

```{r}
test <- lee98_forward(
  wavelength = wavelength,
  iop = iop,
  view = 40,
  sun = 20,
  h_w = 2, # bottom depth
  optically_shallow = T,
  rrs_bottom = rrs_bottom,
  verbose = T
)
```

## saber forward (am03 ?)

```{r}
init_rrs <- saber_forward(
  wavelength = wavelength,
  iop = iop,
  water_type = 2,
  view = 0,
  sun = 20,
  optically_shallow = T,
  h_w = 2,
  rrs_bottom = rrs_bottom,
  verbose = T
)
```

