---
title: "Introduction to SABER MCMC"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SABER}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(SABER)
library(plotly)
library(BayesianTools)
library(stringr)
library(dplyr)
library(tidyr)
library(lubridate)

font <- list(family = "Times New Roman", size = 20, weight = "normal")

border <- list(
  type = "rect",
  fillcolor = "transparent",
  line = list(width = 0.5),
  xref = "paper",
  yref = "paper",
  x0 = 0,
  x1 = 1,
  y0 = 0,
  y1 = 1
)

library(reticulate)
use_condaenv("kaleido", required = TRUE)
py_config()
py_run_string("import sys")

here <- function(...) {
  start <- "/D/Documents/phd/thesis"
  file.path(start, ...)
}
```

## Overview

SABER is an R package for Bayesian inversion of radiative transfer models using in-situ data and prior distribution fitting.

## Fully unconstrained inversion with uniform priors

```{r}
rrs <- rrs_hw %>%
  filter(
    wavelength > 400, wavelength < 720, 
    ensemble == 1657138160
    ) %>%
  mutate(rrs_0m = rrs_0p_to_0m(rrs_estimate)) %>%
  select(wavelength, rrs_0m)
```

```{r}
par_fixed <- c(
  "water_type" = 2,
  "theta_view" = 0,
  "theta_sun" = 20,
  "sd" = 1
)

par_estimates <- inverse_mcmc(
  rrs = rrs,
  forward_model = "am03",
        par_inversed = c("chl", "a_g_440", "a_g_s", "bb_p_550", "bb_p_gamma", "h_w", "r_rs_b_saccharina", "r_rs_b_cca", "r_rs_b_gravel"),
        prior = NULL,
        lower = c(0, 0, 0, 0, 0, 0, 0, 0, 0),
        best = c(1, 4, 0.017, 0.04, 0.46, 5, 0.5, 0.1, 0.25),
        upper = c(100, 10, 1, 0.5, 5, 20, 1, 0.15, 1),
  par_fixed = par_fixed,
  iterations = 5e4,
  burnin = 5e3,
  sampler = "DEzs"
)

# plot(out)
```

Now we can compare what those OAC gives in "am03" and compare that with our input rrs.

```{r}
# par_estimates <- tibble(
#   name = names(MAP(out)[[1]]),
#   value = MAP(out)[[1]]
# ) %>%
#   filter(name %in% c("chl", "a_g_440", "bb_p_550", "h_w"))
#
# par_estimates <- stats::setNames(par_estimates$value, par_estimates$name)

iop <- iop_from_oac(
  rrs$wavelength,
  par_estimates
)


r_b_fraction_vec <- par_estimates[grepl("^r_rs_b(?!.*_sd$)", names(par_estimates), perl = TRUE)]

rrs_bottom <- compute_r_rs_b_lmm(
  fractions = r_b_fraction_vec
)

rrs_retrieved <- forward_am03(
  wavelength = rrs$wavelength,
  iop = iop,
  water_type = 2,
  theta_view = 0,
  theta_sun = 20,
  h_w = par_estimates["h_w"],
  r_b = rrs_bottom
)

sub_par <- par_estimates[1:9]

ply <- plot_ly() %>%
  add_lines(x = rrs$wavelength, y = rrs$rrs_0m, name = "rrs_observed") %>%
  add_lines(x = rrs$wavelength, y = rrs_retrieved, name = "rrs_retrieved") %>% 
  add_annotations(
    text = ~paste(glue::glue("{names(sub_par)}: {round(sub_par, 3)}"), collapse = "\n"),
    textangle = 0,
    x = 1,
    xshift = 0,
    y = 1,
    yref = "paper",
    xref = "paper",
    xanchor = "top-left",
    yanchor = "top-left",
    showarrow = FALSE,
    font = font
  ) %>%
  layout(
    yaxis = list(
      title = TeX("R_\\text{rs}(0^-) [\\text{sr}^{-1}]")
    ),
    xaxis = list(
      title = TeX("\\text{wavelength} [\\text{nm}]")
    ),
    font = font,
    shapes = list(border),
    legend = list(
      font = list(
        size = 20),
      bgcolor = "rgba(105, 159, 245, 0.0)",#"#FFFFFF",
      xanchor = "top-right",
      yanchor = "top-right",
      x = 0.1,
      y = 1
    )
  ) %>%
  config(mathjax = "cdn", displayModeBar = T)

ply

# save_image(ply, here("2_chapter/figure/rrs_input_estimates_output_unconstrained.png"), width = 800, height = 700, scale = 4)
```

### Bottom reflectance retrieval

```{r}
r_rs_b_retrieved_unconstrained <- retrieve_r_rs_b_am03(
  wavelength = rrs$wavelength,
  iop = iop,
  r_rs = rrs$rrs_0m,
  water_type = 2,
  theta_view = 0,
  theta_sun = 20,
  h_w = par_estimates["h_w"]
)

ply <- plot_ly() %>%
  add_lines(x = rrs$wavelength, y = r_rs_b_retrieved_unconstrained, name = "r_rs_b_unconstrained") %>%
  layout(
    yaxis = list(
      title = TeX("R_\\text{rs}(\\text{bottom}) [sr^{-1}]")#,
      # range = c(-0.01, 0.6)
      ),
    xaxis = list(
      title = TeX("\\text{wavelength}[\\text{nm}]")
      ),
    font = font,
    shapes = list(border)
  ) %>%
  config(mathjax = "cdn", displayModeBar = T)

ply
# save_image(ply, here("2_chapter/figure/retrieved_bottom_reflectance_unconstrained.png"), width = 800, height = 700, scale = 4)
```

### Batch processing

```{r}
ensembles <- unique(rrs_hw$ensemble)

ensembles <- ensembles[
  ensembles > as.numeric(ymd_hms("2022-07-06 20:58:20")) &
    ensembles > as.numeric(ymd_hms("2022-07-06 21:04:50"))
]

rrs_hw_sub <- rrs_hw %>%
  # filter(ensemble %in% ensembles) %>%
  filter(wavelength > 400, wavelength < 720,) %>%
  mutate(
    rrs_0m = rrs_0p_to_0m(rrs_estimate),
    h_w = altitude_m + abs(bottom_elevation_m)
  )

rrs_hw_sub <- rrs_hw_sub %>%
  group_by(ensemble) %>%
  nest() %>%
  mutate(
    pass = purrr::map(
      .x = data, ~ any(.x$rrs_unc > 0.002, na.rm = T)
    )
  ) %>%
  filter(
    pass == F
  ) #%>%
  # unnest(cols=c(data))

# Split by ensemble
# rrs_split <- split(rrs_hw_sub, rrs_hw_sub$ensemble)

# Build traces for each ensemble
traces <- purrr::map2(rrs_hw_sub$ensemble, rrs_hw_sub$data, function(ensemble, df) {
  ens_name <- unique(ensemble)

  plot_ly(data = df) %>%
    add_ribbons(
      x = ~wavelength,
      ymin = ~rrs_estimate - rrs_unc,
      ymax = ~rrs_estimate + rrs_unc,
      name = paste0(ens_name, " (uncertainty)"),
      legendgroup = ens_name,
      line = list(color = "transparent"),
      fillcolor = NULL,
      showlegend = FALSE
    ) %>%
    add_lines(
      x = ~wavelength,
      y = ~rrs_estimate,
      name = ens_name,
      legendgroup = ens_name
    )
})

rrs_hw_sub <- rrs_hw_sub %>%
  unnest(cols=c(data))

ply <- traces[[140]]#purrr::reduce(traces, add_trace)
ply
```

```{r}
par_fixed <- c(
  "water_type" = 2,
  "theta_view" = 0,
  "theta_sun" = 20,
  "sd" = 1
)

inversed_data <- rrs_hw_sub %>%
  group_by(ensemble) %>%
  nest() %>%
  mutate(
    par_inversed = purrr::map(
      .x = data,
      ~ {message(ensemble)
        inverse_mcmc(
          rrs = .x,
          forward_model = "am03",
          par_inversed = c("chl", "a_g_440", "a_g_s", "bb_p_550", "bb_p_gamma", "h_w", "r_rs_b_saccharina", "r_rs_b_cca", "r_rs_b_gravel"),
          prior = NULL,
          lower = c(0, 0, 0, 0, 0, 0, 0, 0, 0),
          best = c(1, 4, 0.017, 0.04, 0.46, 5, 0.5, 0.25, 0.25),
          upper = c(100, 10, 1, 0.5, 5, 20, 1, 1, 1),
          par_fixed = par_fixed,
          iterations = 5e4,
          burnin = 5000,
          sampler = "DEzs"
        )}
    )
  )
```

```{r}
par_inversed <- inversed_data$par_inversed %>%
  bind_rows() %>%
  rename_with(.fn = ~ paste0(.x, "_estim")) %>%
  mutate(ensemble = inversed_data$ensemble, .before = 1)

compare_h_w <- rrs_hw_sub %>%
  select(ensemble, lat, lon, h_w, plant_height_m, percent_coverage) %>%
  unique() %>%
  inner_join(par_inversed, by = c("ensemble"))

# readr::write_csv(compare_h_w, "~/compare_h_w.csv")
```

```{r}
ply <- plot_ly(compare_h_w) %>%
  add_markers(
    x = ~h_w,
    y = ~h_w_estim,
    color = ~if_else(ensemble == 1657138160, I("red"), I("blue")),
    text = ~ensemble
    ) %>%
  layout(
    font=font,
    
    xaxis = list(
      title = list(
        text = TeX("h_\\text{w}[\\text{m}]\\ \\text{measured}")
      )
    ),
    yaxis = list(
      title = list(
        text = TeX("\\hat{h_\\text{w}}[\\text{m}]\\ \\text{retrieved}")
      )
    ),
    shapes = list(
      border,
      list(
        type = "line",
        x0 = ~ min(h_w, h_w_estim),
        x1 = ~ max(h_w, h_w_estim),
        xref = "x",
        y0 = ~ min(h_w, h_w_estim),
        y1 = ~ max(h_w, h_w_estim),
        yref = "y",
        line = list(color = "black")
      )
    )
  ) %>%
  config(mathjax = "cdn", displayModeBar = T)


ply

# save_image(ply, here("2_chapter/figure/h_w_retrieved_5e4.png"), width = 700, height = 700, scale = 4)
```

## Water depth constrained inversion

```{r}
# How to retrieve bottom reflectance without specifying a class ?
# Is it feasible ? Definitely seems useful.
par_fixed <- c(
  "water_type" = 2,
  "theta_view" = 0,
  "theta_sun" = 20,
  "h_w" = 4.34,
  "sd" = 1
)

par_estimates <- inverse_mcmc(
  rrs = rrs,
  forward_model = "am03",
          par_inversed = c("chl", "a_g_440", "a_g_s", "bb_p_550", "bb_p_gamma", "h_w", "r_rs_b_saccharina", "r_rs_b_cca", "r_rs_b_gravel"),
          prior = NULL,
          lower = c(0, 0, 0, 0, 0, 0, 0, 0, 0),
          best = c(1, 4, 0.017, 0.04, 0.46, 5, 0.5, 0.25, 0.25),
          upper = c(100, 10, 1, 0.5, 5, 20, 1, 1, 1),
  par_fixed = par_fixed,
  iterations = 5e4,
  burnin = 2000,
  sampler = "DEzs"
)

# plot(out)
```

```{r}
# par_estimates <- tibble(
#   name = names(MAP(out)[[1]]),
#   value = MAP(out)[[1]]
# ) %>%
#   filter(name %in% c("chl", "a_g_440", "bb_p_550", "h_w"))
#
# par_estimates <- stats::setNames(par_estimates$value, par_estimates$name)

iop <- iop_from_oac(
  rrs$wavelength,
  par_estimates
)


r_b_fraction_vec <- par_estimates[grepl("^r_rs_b(?!.*_sd$)", names(par_estimates), perl = TRUE)]

rrs_bottom <- compute_r_rs_b_lmm(
  fractions = r_b_fraction_vec
)

rrs_retrieved <- forward_am03(
  wavelength = rrs$wavelength,
  iop = iop,
  water_type = 2,
  theta_view = 0,
  theta_sun = 20,
  h_w = par_fixed["h_w"],
  r_b = rrs_bottom
)

sub_par <- par_estimates[1:6]

ply <- plot_ly() %>%
  add_lines(x = rrs$wavelength, y = rrs$rrs_0m, name = "rrs_observed") %>%
  add_lines(x = rrs$wavelength, y = rrs_retrieved, name = "rrs_retrieved") %>% 
  add_annotations(
    text = ~paste(glue::glue("{names(sub_par)}: {round(sub_par, 3)}"), collapse = "\n"),
    textangle = 0,
    x = 1,
    xshift = 0,
    y = 1,
    yref = "paper",
    xref = "paper",
    xanchor = "top-left",
    yanchor = "top-left",
    showarrow = FALSE,
    font = font
  ) %>%
  layout(
    yaxis = list(
      title = TeX("R_\\text{rs}(0^-) [\\text{sr}^{-1}]")
    ),
    xaxis = list(
      title = TeX("\\text{wavelength} [\\text{nm}]")
    ),
    font = font,
    shapes = list(border),
    legend = list(
      font = list(
        size = 20),
      bgcolor = "rgba(105, 159, 245, 0.0)",#"#FFFFFF",
      xanchor = "top-right",
      yanchor = "top-right",
      x = 0.1,
      y = 1
    )
  ) %>%
  config(mathjax = "cdn", displayModeBar = T)

ply

# save_image(ply, here("2_chapter/figure/rrs_input_estimates_output_constrained_hw.png"), width = 800, height = 700, scale = 4)
```

```{r}
r_rs_b_retrieved_constrained <- retrieve_r_rs_b_am03(
  wavelength = rrs$wavelength,
  iop = iop,
  r_rs = rrs$rrs_0m,
  water_type = 2,
  theta_view = 0,
  theta_sun = 20,
  h_w = par_fixed["h_w"]
)

ply <- plot_ly() %>%
  add_lines(x = rrs$wavelength, y = r_rs_b_retrieved_constrained, name = "r_rs_b_constrained") %>%
  add_lines(x = rrs$wavelength, y = r_rs_b_retrieved_unconstrained, name = "r_rs_b_unconstrained") %>%
  layout(
    yaxis = list(
      title = TeX("R_\\text{rs}(\\text{bottom}) [sr^{-1}]"),
      range = c(-0.01, 0.4)
      ),
    xaxis = list(
      title = TeX("\\text{wavelength}[\\text{nm}]")
      ),
    legend = list(
      font = list(
        size = 20),
      bgcolor = "rgba(105, 159, 245, 0.0)",#"#FFFFFF",
      xanchor = "top-right",
      yanchor = "top-right",
      x = 0.5,
      y = 1
    ),
    font = font,
    shapes = list(border)
  ) %>%
  config(mathjax = "cdn", displayModeBar = T)

ply
# save_image(ply, here("2_chapter/figure/retrieved_bottom_reflectance_constrained_hw.png"), width = 800, height = 700, scale = 4)
```
