---
title: "parameter_space"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SABER)
library(plotly)

font <- list(family = "Times New Roman", size = 20, weight = "normal")

border <- list(
  type = "rect",
  fillcolor = "transparent",
  line = list(width = 0.5),
  xref = "paper",
  yref = "paper",
  x0 = 0,
  x1 = 1,
  y0 = 0,
  y1 = 1
)

library(reticulate)
use_condaenv("kaleido", required = TRUE)
py_config()
py_run_string("import sys")

here <- function(...) {
  start <- "/D/Documents/phd/thesis"
  file.path(start, ...)
}
```

```{r}
r_frac <- c("r_rs_b_saccharina" = 1)#, "r_rs_b_cca" = 0.008, "r_rs_b_gravel" = 0.013)

r_rs_b_saccharina <- compute_r_rs_b_lmm(r_frac)
```

```{r}
rrs_observed <- rrs_hw %>%
  filter(
    wavelength > 400, wavelength < 720,
    # ensemble == 1657138160
    ensemble == 1657138460
    ) %>%
  mutate(rrs_0m = rrs_0p_to_0m(rrs_estimate)) %>%
  select(wavelength, rrs_0m)

wavelength <- unique(rrs_observed$wavelength)
rrs_observed <- rrs_observed$rrs_0m
```

# Cartesian product of parameters

```{r}
chl <- seq(0.0001, 50, by = 1)
# a_g_440 <- seq(0.0001, 15, by = 1)
# bb_p_550 <- seq(0.000001, 0.01, by = 0.001)
h_w <- seq(0.1, 10, by = 0.1)
a_g_440 <- 0.1
bb_p_550 <- 0.01
# h_w <- 4

parameter_space <- expand.grid(
  list(
    "chl" = chl,
    "a_g_440" = a_g_440,
    "bb_p_550" = bb_p_550,
    "h_w" = h_w
    )
  )
```

# Compute likelihood over parameter space

```{r}
test <- purrr::map_df(
  # .progress = T,
  .x = seq_along(parameter_space[,1]),
  function(x) {
    oac <- c("chl" = parameter_space[x, 1],
             "a_g_440" = parameter_space[x, 2],
             "bb_p_550" = parameter_space[x, 3]
    )
    
    iop <- iop_from_oac(wavelength, oac)
    
    rrs_modelled = forward_am03(
      wavelength = wavelength,
      iop = iop,
      water_type = 2,
      theta_sun = 20, theta_view = 0,
      h_w = parameter_space[x, 4],
      r_b = r_rs_b_saccharina
    )
    
    rrs_observed <- na.omit(rrs_observed)
    rrs_modelled <- na.omit(rrs_modelled)
    # browser()
    
    log_ll <- sum(dnorm(x = 10000 * rrs_observed, mean = 10000 * rrs_modelled, sd = 1, log = TRUE))
    
    tibble(
      parameter_space_id = x,
      log_ll
    )
  }
)
```

# Plot

```{r}
ply <- test %>%
  #arrange(log_ll) %>%
  mutate(sorted_id = seq_along(log_ll)) %>%
  plot_ly() %>%
  add_lines(x = ~ sorted_id, y = ~log_ll)

ply
```

