---
title: "Introduction to SABER MCMC"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SABER}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
# library(SABER)
# devtools::load_all(".")
library(SABER)

library(plotly)
library(stringr)
library(dplyr)
library(tidyr)
library(lubridate)
library(cmdstanr)
library(purrr)
library(posterior)
library(matrixStats)
library(glue)

font <- list(family = "Times New Roman", size = 20, weight = "normal")

border <- list(
  type = "rect",
  fillcolor = "transparent",
  line = list(width = 0.5),
  xref = "paper",
  yref = "paper",
  x0 = 0,
  x1 = 1,
  y0 = 0,
  y1 = 1
)

library(reticulate)
use_condaenv("kaleido", required = TRUE)
py_config()
py_run_string("import sys")

here <- function(...) {
  start <- "/D/Documents/phd/thesis"
  file.path(start, ...)
}
```

## Overview

SABER is an R package for Bayesian inversion of radiative transfer models using in-situ data and prior distribution fitting.

## Compile STAN model

```{r}
# model <- cmdstan_model("/home/raphael/CLionProjects/saber-lib/src/model.stan")

model <- cmdstan_model(
  stan_file = "/home/raphael/R/SABER/inst/stan/model_uc.stan",
  # stan_file = "/home/raphael/R/SABER/inst/stan/model_hc.stan",
  # stan_file = "/home/raphael/R/SABER/inst/stan/model_fc.stan",
  user_header = "/home/raphael/R/SABER/inst/stan/fct_rtm_stan.hpp"
)

# cpp_options = list(stan_threads = TRUE)
```

## Single ensemble processing (test)

```{r}
rrs <- rrs_hw %>%
  filter(
    wavelength > 370, wavelength < 800,
    ensemble == 1657138160
    # ensemble == 1657138460
    ) %>%
  mutate(rrs_0m = rrs_0p_to_0m(rrs_estimate)) %>%
  select(wavelength, rrs_0m, rrs_unc, theta_sun = sol_zen, h_w = bottom_elevation_mu)
```

```{r}
#unique(r_b_gamache$class)

# --- Build Stan base data (done once per wavelength grid) ---
stan_data_base <- make_stan_data_base(
  wavelength = rrs$wavelength,
  water_type = 2,
  theta_view = 0,
  shallow = 1,
  bottom_class_names = c("coraline_crustose_algae", "saccharina_latissima", "sediment"),
  a_gnap_s = 0.0156,
  bb_p_gamma = 0.38
)

# --- Prepare observation-specific inputs (with realistic sigma floor) ---
obs <- make_stan_data_obs(
  df = rrs,
  stan_data_base = stan_data_base,
  use_measured_sigma = TRUE,
  sigma_floor = 1e-8    # IMPORTANT: avoid pathological curvature
)

stan_data <-make_stan_data(
  stan_data_base,
  obs
)

# --- Run Stan (light but robust defaults) ---
fit <- fit_one(
  mod = model,
  stan_data = stan_data,
  mode = "sample",
  chains = 2,
  iter_warmup = 300,
  iter_sampling = 300,
  adapt_delta = 0.85,
  max_treedepth = 12,
  seed = 123
)

# --- Sampler diagnostics (why fast/slow) ---
diag <- sampler_diag_stats(fit)
print(diag)
```

```{r}
# --- Parameter summaries (including bottom_mix + s_class) ---
# par_vars <- c(
#   "chl","a_g_440","a_nap_440","bb_p_550","h_w",
#   "bottom_mix"
# )

# par_vars = # c("chl","a_g_440","a_nap_440","bb_p_550","h_w","bottom_mix","a_bottom"),
#          # c("chl","a_g_440","a_nap_440","bb_p_550","h_w","bottom_mix"),
#           c("chl","a_g_440","a_nap_440", "a_nap_s", "a_g_s", "bb_p_550", "bb_p_gamma", "h_w","bottom_w", "sigma_model")

# par_vars <- c("chl","a_g_440","a_nap_440", "a_nap_s", "a_g_s", "bb_p_550",
#               "bb_p_gamma", "h_w","bottom_w", "sigma_model")

par_vars <- c("chl","a_gnap_440","bb_p_550","h_w","r_b_mix",
              "r_b_a")

# par_vars <- c("chl","a_g_440","a_nap_440","bb_p_550","r_b_mix",
#               "r_b_a")

par_sum <- summarize_params_fast(fit, par_vars)
print(par_sum)
```

```{r}
spec <- summarize_rrs_hat_fast(fit, probs = c(0.05, 0.95))

metrics <- fit_metrics_1(
  rrs_obs = obs$rrs_obs,
  mean_hat = spec$rrs_hat,
  q_lo = spec$rrs_q_lo,
  q_hi = spec$rrs_q_hi,
  sigma_vec = obs$sigma_rrs
)
print(metrics)
```

```{r}
# --- Plot: observed vs posterior ---
library(plotly)

plot_ly() %>%
  add_lines(
    x = obs$wl,
    y = obs$rrs_obs,
    name = "Observed Rrs"
  ) %>%
  add_ribbons(
    x = obs$wl,
    ymin = obs$rrs_obs - obs$sigma_rrs,
    ymax = obs$rrs_obs + obs$sigma_rrs,
    name = "sigma_rrs",
    hoverinfo = "skip",
    line = list(width = 0)
  ) %>%
  add_lines(
    x = obs$wl,
    y = spec$rrs_hat,
    name = "Posterior mean",
    line = list(width = 3)
  ) %>%
  add_ribbons(
    x = obs$wl,
    ymin = spec$rrs_q_lo,
    ymax = spec$rrs_q_hi,
    name = "90% CI",
    hoverinfo = "skip",
    line = list(width = 0)
  ) %>%
  layout(
    xaxis = list(title = "Wavelength [nm]"),
    yaxis = list(title = "Rrs(0−) [sr⁻¹]"),
    title = paste(
      "Single ensemble inversion",
      "<br>",
      paste(names(metrics), round(unlist(metrics), 3), collapse = " | ")
    )
  )
```
Plot for bottom spectrum if spectrally inversed.

```{r}
# spec %>%
#   plot_ly(
#     x = obs$wl
#     ) %>%
#   add_lines(
#     y = spec$r_b_hat
#     ) %>%
#   add_ribbons(
#     ymin = spec$r_b_q_lo,
#     ymax = spec$r_b_q_hi
#   )
```


## Batch processing (production)

```{r}
# ensembles <- unique(rrs_hw$ensemble)
# 
# t0 <- as.numeric(ymd_hms("2022-07-06 20:58:20"))
# t1 <- as.numeric(ymd_hms("2022-07-06 21:04:50"))
# ensembles <- ensembles[ensembles >= t0 & ensembles <= t1]
# 
# 
# rrs_hw_sub <- rrs_hw %>%
#   filter(wavelength > 370, wavelength < 800) %>%
#   mutate(
#     rrs_0m = rrs_0p_to_0m(rrs_estimate),
#     h_w_meas = altitude_mu + abs(bottom_elevation_mu),
#     theta_sun = sol_zen
#   )

# rrs_hw_sub <- rrs_hw_gamache %>%
#   filter(wavelength > 370, wavelength < 800) %>%
#   mutate(
#     rrs_0m = rrs_0p_to_0m(rrs_estimate),
#     h_w_meas = abs(h_w)
#   )

# gamache <- readr::read_csv(here("4_chapter/data/algae-wise/2022-07-05_gamache_bay_jet-ski.csv"))
# 
# time_limits <- list(
#   interval(ymd_hms("2022-07-05 14:12:15"), ymd_hms("2022-07-05 14:20:20")),
#   interval(ymd_hms("2022-07-05 13:24:00"), ymd_hms("2022-07-05 13:30:30")),
#   interval(ymd_hms("2022-07-05 12:56:00"), ymd_hms("2022-07-05 13:00:00")),
#   interval(ymd_hms("2022-07-05 12:28:34"), ymd_hms("2022-07-05 12:30:11"))
#   #interval(ymd_hms("2022-07-05 13:20:43"), ymd_hms("2022-07-05 13:45:52"))
# )
# 
# rrs_hw_sub <- gamache %>%
#   mutate(
#     # date_time = as.POSIXct(date_time, origin="1970-01-01"),
#     date_time_hocr = as_datetime(date_time),
#     date_time = as_datetime(round(date_time)),
#     group = case_when(
#       date_time %within% time_limits[1] ~ 37,
#       date_time %within% time_limits[2] ~ 44,
#       date_time %within% time_limits[3] ~ 48,
#       date_time %within% time_limits[4] ~ 52
#       )
#     ) %>%
#   filter(date_time %within% time_limits) %>%
#   filter(wavelength > 370, wavelength < 800) %>%
#   mutate(
#     rrs_0m = rrs_0p_to_0m(rrs_estimate),
#     h_w_meas = abs(h_w)
#   )

rrs_hw_sub <- readr::read_csv(here("4_chapter/data/algae-wise/rrs_iop_matchup.csv")) %>%
  filter(wavelength > 370, wavelength < 800) %>%
  mutate(
    rrs_0m = rrs_0p_to_0m(rrs_estimate),
    theta_sun = sol_zen,
    h_w_meas = abs(h_w)
  )

rrs_hw_sub <- rrs_hw_sub %>%
  group_by(ensemble) %>%
  nest() %>%
  mutate(
    pass = purrr::map_lgl(data, ~ any(.x$rrs_unc > 0.001 | is.na(.x$rrs_estimate), na.rm = TRUE))
  ) %>%
  filter(pass == FALSE)# & ensemble %in% ensembles)

# build base once (same wavelength grid!)
stan_data_base <- make_stan_data_base(
  wavelength = rrs_hw_sub[[1,2]][[1]]$wavelength,
  water_type = 2,
  theta_view = 0,
  shallow = 1,
  bottom_class_names = c("coraline_crustose_algae", "saccharina_latissima", "sediment"),
  a_gnap_s = 0.0156,
  bb_p_gamma = 0.38
)

# rrs_hw_sub[[1,2]][[1]]$wavelength
```

```{r}
# results <- run_batch(
#   rrs_hw_sub = rrs_hw_sub,
#   mod = model,
#   stan_data_base = stan_data_base,
#   out_dir = "/D/Documents/phd/thesis/4_chapter/data/stan/ensemble",
#   mode = "sample",
#   chains = 2, iter_warmup = 300, iter_sampling = 300,
#   adapt_delta = 0.85
# )

library(progressr)
handlers("txtprogressbar")

# If you parallelize across ensembles, keep threads_per_chain small (often 1)
results <- run_batch_parallel(
  rrs_hw_sub = rrs_hw_sub,
  mod = model,
  stan_data_base = stan_data_base,
  workers = 5,
  threads_per_chain = 1
)
```

```{r}
# saveRDS(results, file = here("4_chapter/data/stan/results_20250108.rds"))
# results <- readRDS(here("4_chapter/data/stan/results.rds"))
```

```{r}
tabs <- extract_batch_tables(results)
plot_batch_diagnostics(tabs$diag)
plot_sampler_cost(tabs$diag)
```

### Hw

```{r}
par_summary <- results %>% 
  mutate(
    par_summary = purrr::map(
      .x = stan,
      ~ pivot_wider(
        data = .x$par_summary,
        names_from = variable,
        names_glue = "{variable}_{.value}",
        values_from = -variable
      )
    ),
    data_select = purrr::map(
      .x = data,
      ~ .x %>% 
        select(
          id,
          date_time_iop,
          lat_iop,
          lon_iop,
          date_time_rrs,
          lat_rrs,
          lon_rrs,
          h_w_meas,
          # plant_height_mu,
          chla_mean_meas = chla_mean,
          chla_sd_meas = chla_sd,
          a_gnap_440_meas = a_gnap_440,
          bbp_555_mean_meas = bbp_555_mean,
          bbp_555_sd_meas = bbp_555_sd,
          a_gnap_s_meas = a_gnap_s,
          bbp_gamma_mean_meas = bbp_gamma_mean,
          bbp_gamma_sd_meas = bbp_gamma_sd
          ) %>%
        distinct()
    )
  ) %>%
  select(ensemble, data_select, par_summary) %>%
  unnest(cols = c(data_select, par_summary))

# readr::write_csv(par_summary, here("4_chapter/data/par_summary_position.csv"))
```

```{r}
library(plotly)

xy_min <- min(par_summary$h_w_meas, par_summary$h_w_mean, na.rm = TRUE) -0.5
xy_max <- max(par_summary$h_w_meas, par_summary$h_w_mean, na.rm = TRUE) +0.5

ply <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~h_w_meas,
    y = ~h_w_mean,
    # color = ~a_dg_440_mean,
    color = ~id,
    text = ~paste0(
      "ensemble: ", ensemble,
      "<br>h_w_meas: ", round(h_w_meas, 2), " m",
      "<br>h_w_estim: ", round(h_w_mean, 2), " m"
    ),
    hoverinfo = "text"
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    xaxis = list(title = "Observed h_w (m)", range = c(xy_min, xy_max)),
    yaxis = list(title = "Retrieved h_w (m)", range = c(xy_min, xy_max)),
    # title = "Retrieved vs Observed Water Depth",
    legend = list(
      font = list(size = 18),
      bgcolor = "rgba(105, 159, 245, 0.0)",
      xanchor = "top-left",
      yanchor = "top-left",
      x = 0.8,
      y = 0.05
    ),
    font = font,
    shapes = list(
      border
    )
  )

ply

# save_image(ply, here("4_chapter/figure/h_w_matchup_.png"), width = 550, height = 550, scale = 4)
```

### IOPs

```{r}
xy_min <- min(par_summary$chla_mean_meas, par_summary$chl_mean, na.rm = TRUE) - 0.1
xy_max <- max(par_summary$chla_mean_meas, par_summary$chl_mean, na.rm = TRUE) + 0.1

ply_chl <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~chla_mean_meas,
    y = ~chl_mean,
    color = ~id,
    showlegend = T
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    xaxis = list(
      title = "chl",
      range = c(xy_min, xy_max)
    ),
    yaxis = list(
      title = "chl_hat",
      range = c(xy_min, xy_max)
    ),
    font = font,
    shapes = list(
      border
    ),
    legend = list(
      font = list(
        size = 20),
      bgcolor = "rgba(255, 255, 255, 1)",#"#FFFFFF",
      xanchor = "top-right",
      yanchor = "top-right",
      x = 0.01,
      y = 0.99
    )
  )
xy_min <- min(par_summary$a_gnap_440_meas, par_summary$a_gnap_440_mean, na.rm = TRUE) - 0.1
xy_max <- max(par_summary$a_gnap_440_meas, par_summary$a_gnap_440_mean, na.rm = TRUE) + 0.1

ply_a_gnap_440 <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~a_gnap_440_meas,
    y = ~a_gnap_440_mean,
    color = ~id,
    showlegend = F
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    xaxis = list(
      range = c(xy_min, xy_max)
    ),
    yaxis = list(
      range = c(xy_min, xy_max)
    ),
    font = font,
    shapes = list(
      border
    )
  )

# xy_min <- min(par_summary$anap_440_meas, par_summary$a_nap_440_mean, na.rm = TRUE) - 0.1
# xy_max <- max(par_summary$anap_440_meas, par_summary$a_nap_440_mean, na.rm = TRUE) + 0.1
# 
# ply_a_nap_440 <- par_summary %>%
#   plot_ly() %>%
#   add_markers(
#     x = ~anap_440_meas,
#     y = ~a_nap_440_mean,
#     color = ~id,
#     showlegend = F
#   ) %>%
#   add_lines(
#     x = c(xy_min, xy_max),
#     y = c(xy_min, xy_max),
#     name = "1:1",
#     line = list(dash = "dash", color = "black"),
#     showlegend = F
#   ) %>%
#   layout(
#     xaxis = list(
#       range = c(xy_min, xy_max)
#     ),
#     yaxis = list(
#       range = c(xy_min, xy_max)
#     ),
#     font = font,
#     shapes = list(
#       border
#     )
#   )

xy_min <- min(par_summary$bbp_555_mean_meas, par_summary$bb_p_550_mean, na.rm = TRUE) - 0.001
xy_max <- max(par_summary$bbp_555_mean_meas, par_summary$bb_p_550_mean, na.rm = TRUE) + 0.001

ply_bb_p_555 <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~bbp_555_mean_meas,
    y = ~bb_p_550_mean,
    color = ~id,
    showlegend = F
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    font = font,
    shapes = list(
      border
    )#,
    # margin = list(l = 70, r = 20, b = 60, t = 20)
  )

ply <- subplot(
  ply_chl,
  ply_a_gnap_440,
  #ply_a_nap_440,
  ply_bb_p_555,
  nrows = 2,
  margin = 0.045
) %>%
  layout(
    xaxis = list(
      title = list(
        text = TeX("\\Large{\\text{chl}}"),
        standoff = 5
        )
    ),
    yaxis = list(
      title = TeX("\\Large{\\widehat{\\text{chl}}}")
    ),
    xaxis2 = list(
      title = list(
        text = TeX("\\Large{a_\\text{g+nap}}(440)"),
        standoff = 5
        )
    ),
    yaxis2 = list(
      title = list(
        text = TeX("\\Large{\\widehat{a_\\text{g+nap}}(440)}"),
        standoff = 5
        )
    ),
    # xaxis3 = list(
    #   title = TeX("\\Large{a_\\text{nap}(440)}")
    # ),
    # yaxis3 = list(
    #   title = TeX("\\Large{\\widehat{a_\\text{nap}}(440)}")
    # ),
    xaxis3 = list(
      title = TeX("\\Large{b_\\text{bp}(550)}")
    ),
    yaxis3 = list(
      title = list(
        text = TeX("\\Large{\\widehat{b_\\text{bp}}(550)}"),
        standoff = 5
        )
    )
  ) %>%
  config(mathjax = "cdn", displayModeBar = FALSE)

ply

# save_image(ply, here("4_chapter/figure/iop_matchup_.png"), width = 1100, height = 1100, scale = 4)
```

### IOPs Spectral slope

```{r}
xy_min <- min(par_summary$a_gnap_s_meas, par_summary$a_gnap_s_mean, na.rm = TRUE) - 0.001
xy_max <- max(par_summary$a_gnap_s_meas, par_summary$a_gnap_s_mean, na.rm = TRUE) + 0.001

ply_a_gnap_s <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~a_gnap_s_meas,
    y = ~a_gnap_s_mean,
    color = ~id,
    showlegend = T
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    xaxis = list(
      range = c(xy_min, xy_max)
    ),
    yaxis = list(
      range = c(xy_min, xy_max)
    ),
    font = font,
    shapes = list(
      border
    ),
    legend = list(
      font = list(
        size = 20),
      bgcolor = "rgba(255, 255, 255, 1)",#"#FFFFFF",
      xanchor = "top-right",
      yanchor = "top-right",
      x = 0.01,
      y = 0.99
    )
  )

# xy_min <- min(par_summary$a_nap_s_meas, par_summary$a_nap_s_mean, na.rm = TRUE) - 0.001
# xy_max <- max(par_summary$a_nap_s_meas, par_summary$a_nap_s_mean, na.rm = TRUE) + 0.001
# 
# ply_a_nap_s <- par_summary %>%
#   plot_ly() %>%
#   add_markers(
#     x = ~a_nap_s_meas,
#     y = ~a_nap_s_mean,
#     color = ~id,
#     showlegend = F
#   ) %>%
#   add_lines(
#     x = c(xy_min, xy_max),
#     y = c(xy_min, xy_max),
#     name = "1:1",
#     line = list(dash = "dash", color = "black"),
#     showlegend = F
#   ) %>%
#   layout(
#     xaxis = list(
#       range = c(xy_min, xy_max)
#     ),
#     yaxis = list(
#       range = c(xy_min, xy_max)
#     ),
#     font = font,
#     shapes = list(
#       border
#     )
#   )

xy_min <- min(par_summary$bbp_gamma_mean_meas, par_summary$bb_p_gamma_mean, na.rm = TRUE) - 0.001
xy_max <- max(par_summary$bbp_gamma_mean_meas, par_summary$bb_p_gamma_mean, na.rm = TRUE) + 0.001

ply_bb_p_gamma <- par_summary %>%
  plot_ly() %>%
  add_markers(
    x = ~bbp_gamma_mean_meas,
    y = ~bb_p_gamma_mean,
    color = ~id,
    showlegend = F
  ) %>%
  add_lines(
    x = c(xy_min, xy_max),
    y = c(xy_min, xy_max),
    name = "1:1",
    line = list(dash = "dash", color = "black"),
    showlegend = F
  ) %>%
  layout(
    font = font,
    shapes = list(
      border
    )
  )

ply <- subplot(
  ply_a_gnap_s,
  # ply_a_nap_s,
  ply_bb_p_gamma,
  nrows = 2,
  margin = 0.03
) %>%
  layout(
    xaxis = list(
      title = list(
        text = TeX("a_\\text{g+nap}(440)"),
        standoff = 5
        )
    ),
    yaxis = list(
      title = TeX("\\widehat{a_\\text{g+nap}(440)}")
    ),
    # xaxis2 = list(
    #   title = list(
    #     text = TeX("a_\\text{naps}(440)"),
    #     standoff = 5
    #     )
    # ),
    # yaxis2 = list(
    #   title = TeX("\\widehat{a_\\text{naps}(440)}")
    # ),
    xaxis2 = list(
      title = TeX("b_\\text{bps}(550)")
    ),
    yaxis2 = list(
      title = TeX("\\widehat{b_\\text{bps}(550)}")
    )
  ) %>%
  config(mathjax = "cdn", displayModeBar = FALSE)

ply

# save_image(ply, here("4_chapter/figure/iop_slope_matchup_.png"), width = 550, height = 1100, scale = 4)
```

### Bottom reflectance

```{r}
test <- results %>%
  mutate(
    r_b = pmap(
      list(
        obs = data,  # list-column containing wavelength + rrs_0m
        stan = stan
      ),
      function(obs, stan) {
        
        par_summary <- pivot_wider(
          data = stan$par_summary,
          names_from = variable,
          names_glue = "{variable}_{.value}",
          values_from = -variable
        )
 
        id = obs$id
        wavelength <- obs$wavelength
        r_rs <- obs$rrs_0m
        theta_sun = unique(obs$theta_sun)
        h_w = par_summary$h_w_mean
        # h_w = obs$h_w_meas
        
        iop <- iop_from_oac(
          wavelength = wavelength,
          a_w = stan_data_base$a_w,
          a0 = stan_data_base$a0,
          a1 = stan_data_base$a1,
          bb_w = stan_data_base$bb_w,
          chl = par_summary$chl_mean,
          a_gnap_440 = par_summary$a_gnap_440_mean,
          bb_p_550 = par_summary$bb_p_550_mean,
          a_gnap_s = par_summary$a_gnap_s_mean,
          bb_p_gamma = par_summary$bb_p_gamma_mean
        )
        
        r_b_hat <- solve_rb_am03(
          wavelength = wavelength,
          a = iop[,1],
          bb = iop[,2],
          water_type = 2,
          theta_sun_deg = theta_sun,
          theta_view_deg = 0,
          h_w = h_w,
          rrs_obs = r_rs
          )
        
        tibble(
          id = id,
          wavelength = wavelength,
          r_b_hat = r_b_hat
          )
        
      }
    )
  )
```

```{r}
test <- test %>%
  select(ensemble, r_b) %>%
  unnest(cols = c(r_b))
```

```{r}
plots <- test %>%
  split(.$id) %>%
  imap(function(df, id) {
    df <- as.data.frame(df)
    # force(df); force(id)
    
    plot_ly(
      data = df,
      x = df$wavelength,
      y = df$r_b_hat,
      color = as.character(df$ensemble),
      type = "scatter",
      mode = "lines"
    ) %>%
      add_annotations(
        text = id,
        x = 0.5,
        y = 1,
        yref = "paper",
        xref = "paper",
        xanchor = "middle",
        yanchor = "top",
        showarrow = FALSE,
        font = list(size = 20)
      ) %>%
      layout(
        yaxis = list(
          range = c(0, 0.2)
          ),
        xaxis = list(
          range = c(380, 720)),
        font = font,
        shapes = list(
          border
        )
      )
  })

# ply_sub <- do.call(
#   subplot,
#   c(plots, list(nrows = length(plots), shareX = TRUE, sharey = TRUE))
# )


ply <- subplot(
  plots,
  nrows = 3,
  shareX = TRUE#,
  # sharey = TRUE
) %>%
  add_annotations(
    text = TeX("\\Large{\\text{Wavelength [nm]}}"),
    yshift = -25,
    x = 0.5,
    y = 0.0,
    yref = "paper",
    xref = "paper",
    xanchor = "middle",
    yanchor = "top",
    showarrow = FALSE,
    font = list(size = 15)
  ) %>%
  add_annotations(
    text = TeX("\\Large{R_\\text{b}}"),
    textangle = -90,
    xshift = -65,
    x = 0,
    y = 0.5,
    yref = "paper",
    xref = "paper",
    xanchor = "middle",
    yanchor = "top",
    showarrow = FALSE,
    font = list(size = 15)
  ) %>%
  layout(
    margin = list(l=68, b = 60),
    showlegend = F
  ) %>%
  config(mathjax = "cdn", displayModeBar = FALSE)

ply

# save_image(ply, here("4_chapter/figure/r_b_.png"), width = 1100, height = 1100, scale = 4)
```


