# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute IOPs from OACs
#'
#' Bio-optical model to compute Inherent Optical Proprieties from Optically Active Constituents
#'
#' @export
iop_from_oac <- function(wavelength, a_w, a0, a1, bb_w, chl, a_gnap_440, bb_p_550, a_gnap_s, bb_p_gamma) {
    .Call(`_SABER_iop_from_oac`, wavelength, a_w, a0, a1, bb_w, chl, a_gnap_440, bb_p_550, a_gnap_s, bb_p_gamma)
}

#' Compute IOPs from OACs
#'
#' Bio-optical model to compute Inherent Optical Proprieties from
#' chl, g+nap(440), bb_p_550
#'
#' @export
iop_from_oac_spm <- function(wavelength, a_w, a0, a1, bb_w, chl, a_g_440, spm, a_nap_star, bb_p_star, a_g_s, a_nap_s, bb_p_gamma) {
    .Call(`_SABER_iop_from_oac_spm`, wavelength, a_w, a0, a1, bb_w, chl, a_g_440, spm, a_nap_star, bb_p_star, a_g_s, a_nap_s, bb_p_gamma)
}

#' Albert & Mobley (2003) Forward Model
#'
#' Computes Rrs below surface using analytical model from Albert & Mobley (2003)
#'
#' @param wavelength vector of wavelengths [nm]
#' @param iop list with elements `a` and `bb`, same length as wavelength
#' @param water_type either 1 or 2 (default = 2)
#' @param theta_sun sun zenith angle [degrees]
#' @param theta_view sensor view angle [degrees]
#' @param h_w optional: water depth [m] (enables shallow mode)
#' @param r_b optional: bottom reflectance vector (same length as wavelength)
#'
#' @return numeric vector of subsurface Rrs
#'
#' @references Albert, A. and Mobley, C.D. (2003) ‘An analytical model for subsurface irradiance and remote sensing reflectance in deep and shallow case-2 waters’, Optics Express, 11(22), pp. 2873–2890. Available at: https://doi.org/10.1364/OE.11.002873.
#' @export
forward_am03 <- function(wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, shallow, h_w, r_b = NULL) {
    .Call(`_SABER_forward_am03`, wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, shallow, h_w, r_b)
}

#' @export
solve_rb_am03 <- function(wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, h_w, rrs_obs) {
    .Call(`_SABER_solve_rb_am03`, wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, h_w, rrs_obs)
}

