# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iop_from_oac <- function(wavelength, a_w, a0, a1, bb_w, chl, a_gnap_440, bb_p_550, a_gnap_s, bb_p_gamma) {
    .Call('_SABER_iop_from_oac', PACKAGE = 'SABER', wavelength, a_w, a0, a1, bb_w, chl, a_gnap_440, bb_p_550, a_gnap_s, bb_p_gamma)
}

forward_am03 <- function(wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, shallow, h_w, r_b = NULL) {
    .Call('_SABER_forward_am03', PACKAGE = 'SABER', wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, shallow, h_w, r_b)
}

solve_rb_am03 <- function(wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, h_w, rrs_obs) {
    .Call('_SABER_solve_rb_am03', PACKAGE = 'SABER', wavelength, a, bb, water_type, theta_sun_deg, theta_view_deg, h_w, rrs_obs)
}

